name: Publish
on:
  push:
    tags:
    - '*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
        with:
          jvm: adopt:8

      - name: Setup PGP Key
        run: |
          echo -n "$PGP_SECRET" | base64 --decode | gpg --batch --import
        env:
          PGP_SECRET: ${{ secrets.PGP_SECRET }}

      - name: Compile everything
        run: sbt "+test"

      - name: Publish release
        env:
          MAVEN_USER: "${{ secrets.SONATYPE_USER }}"
          MAVEN_PASSWORD: "${{ secrets.SONATYPE_PASSWORD }}"
          PGP_PASSPHRASE: "${{ secrets.PGP_PASSWORD }}"
        run: sbt "clean; +publishSigned"
